export const LOBBY_ERROR_CODES = [
    "NOT_HOST",
    "ROOM_NOT_WAITING",
    "NOT_ENOUGH_PLAYERS",
    "PLAYERS_NOT_READY",
    "INVALID_PAYLOAD"
];
export const LOBBY_START_FAILURE_CODES = [
    "TRANSFER_TIMEOUT",
    "MATCH_ROOM_CREATION_FAILED",
    "START_CANCELLED"
];
export const GAME_ERROR_CODES = [
    "NOT_ACTIVE_PLAYER",
    "INVALID_TURN_PHASE",
    "PROPERTY_NOT_BUYABLE",
    "INSUFFICIENT_FUNDS",
    "MATCH_NOT_PLAYING",
    "PLAYER_ELIMINATED",
    "INVALID_PAYLOAD"
];
export const TILE_RESOLUTION_SUMMARY_CODES = [
    "LANDED_ON_START",
    "PROPERTY_AVAILABLE",
    "PAID_RENT",
    "PAID_TAX",
    "WENT_TO_JAIL",
    "NO_EFFECT"
];
